# Generated by Django 6.0.3 on 2026-04-02 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.room'),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(fields=['slug'], name='event_categ_slug_60aed0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(fields=['name'], name='event_categ_name_924f9a_idx'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='events.eventcategory'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_fields', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_at'], name='events_status_eb474e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'start_at'], name='events_categor_cbda7a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', 'status'], name='events_created_d21bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['room', 'start_at'], name='events_room_id_932afa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_at', 'end_at'], name='events_start_a_3ebd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventinvitation',
            index=models.Index(fields=['event', 'status'], name='event_invit_event_i_c3b3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventinvitation',
            index=models.Index(fields=['email'], name='event_invit_email_18ca2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventinvitation',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='uq_event_invites_event_email'),
        ),
        migrations.AddIndex(
            model_name='eventorganizer',
            index=models.Index(fields=['event', 'role'], name='event_organ_event_i_2f1542_idx'),
        ),
        migrations.AddIndex(
            model_name='eventorganizer',
            index=models.Index(fields=['user', 'role'], name='event_organ_user_id_37067a_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventorganizer',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='uq_event_organizers_event_user'),
        ),
        migrations.AddIndex(
            model_name='registrationformfield',
            index=models.Index(fields=['event', 'sort_order'], name='registratio_event_i_42e41e_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationformfield',
            index=models.Index(fields=['event', 'field_type'], name='registratio_event_i_129f43_idx'),
        ),
        migrations.AddConstraint(
            model_name='registrationformfield',
            constraint=models.UniqueConstraint(fields=('event', 'key'), name='uq_registration_fields_event_key'),
        ),
    ]
