# Generated by Django 5.1.15 on 2026-04-12 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registrationformfield",
            name="uq_registration_fields_event_key",
        ),
        migrations.RemoveIndex(
            model_name="eventorganizer",
            name="event_organ_event_i_2f1542_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventorganizer",
            name="event_organ_user_id_37067a_idx",
        ),
        migrations.RenameField(
            model_name="eventorganizer",
            old_name="role",
            new_name="organizer_role",
        ),
        migrations.RenameField(
            model_name="registrationformfield",
            old_name="key",
            new_name="field_key",
        ),
        migrations.RemoveField(
            model_name="event",
            name="capacity",
        ),
        migrations.AddField(
            model_name="event",
            name="cover_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="deep_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="location_snapshot",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="max_capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="icon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventinvitation",
            name="invite_channel",
            field=models.CharField(
                choices=[("email", "Email"), ("contact", "Contact"), ("link", "Link")],
                default="email",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventinvitation",
            name="invite_target",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="eventinvitation",
            name="inviter_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventinvitation",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventinvitation",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventorganizer",
            name="joined_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="registrationformfield",
            name="is_editable_after_submit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventinvitation",
            name="invited_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_event_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registrationformfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("date", "Date"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="eventorganizer",
            index=models.Index(
                fields=["event", "organizer_role"],
                name="event_organ_event_i_8d562c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventorganizer",
            index=models.Index(
                fields=["user", "organizer_role"], name="event_organ_user_id_11ea17_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationformfield",
            constraint=models.UniqueConstraint(
                fields=("event", "field_key"), name="uq_registration_fields_event_key"
            ),
        ),
    ]
