sonar.projectKey=uevent-backend
sonar.projectName=UEvent Backend

# Thư mục chứa source code
sonar.sources=apps,common,core

# Các file/thư mục cần bỏ qua không quét (như thư mục migration, tests, môi trường ảo)
sonar.exclusions=**/migrations/**,**/tests/**,**/test_*.py,venv/**,.venv/**,**/*.html,**/*.css,**/*.js

# Thông tin về Python
sonar.language=py
sonar.python.version=3.x

# Cấu hình encoding
sonar.sourceEncoding=UTF-8
