# Generated by Django 6.0.3 on 2026-04-02 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['event', 'rating'], name='event_feedb_event_i_47fed1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['created_at'], name='event_feedb_created_779e5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventfeedback',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='uq_event_feedbacks_event_user'),
        ),
        migrations.AddIndex(
            model_name='eventquestion',
            index=models.Index(fields=['event', 'moderation_status', 'created_at'], name='event_quest_event_i_ecafb4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventquestion',
            index=models.Index(fields=['user', 'created_at'], name='event_quest_user_id_3f82a6_idx'),
        ),
    ]
