# Generated by Django 5.1.15 on 2026-04-12 15:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0003_remove_registrationformfield_uq_registration_fields_event_key_and_more",
        ),
        ("interactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="eventfeedback",
            name="event_feedb_event_i_47fed1_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventquestion",
            name="event_quest_event_i_ecafb4_idx",
        ),
        migrations.RenameField(
            model_name="eventfeedback",
            old_name="comment",
            new_name="content",
        ),
        migrations.AddField(
            model_name="eventquestion",
            name="answer_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventquestion",
            name="answered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answered_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventquestion",
            name="asked_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="eventquestion",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventfeedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="eventfeedback",
            index=models.Index(
                fields=["event", "created_at"], name="event_feedb_event_i_e1f7d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventquestion",
            index=models.Index(
                fields=["event", "moderation_status", "asked_at"],
                name="event_quest_event_i_145f84_idx",
            ),
        ),
    ]
