# Generated by Django 5.1.15 on 2026-04-12 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0003_remove_registrationformfield_uq_registration_fields_event_key_and_more",
        ),
        ("moderation", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="actor",
        ),
        migrations.RemoveIndex(
            model_name="moderationlog",
            name="moderation__target__c792da_idx",
        ),
        migrations.RemoveIndex(
            model_name="moderationlog",
            name="moderation__actor_i_267439_idx",
        ),
        migrations.RenameIndex(
            model_name="moderationlog",
            new_name="event_moder_event_i_7b0adf_idx",
            old_name="moderation__event_i_f1d204_idx",
        ),
        migrations.RemoveField(
            model_name="moderationlog",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="moderationlog",
            name="target_id",
        ),
        migrations.RemoveField(
            model_name="moderationlog",
            name="target_type",
        ),
        migrations.AddField(
            model_name="moderationlog",
            name="admin_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_moderation_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moderationlog",
            name="report_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="moderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("request_revision", "Request revision"),
                    ("lock", "Lock"),
                    ("delete", "Delete"),
                    ("reopen", "Reopen"),
                    ("escalate", "Escalate"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="moderationlog",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_logs",
                to="events.event",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="moderationlog",
            index=models.Index(
                fields=["admin_user", "created_at"],
                name="event_moder_admin_u_3c466b_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="moderationlog",
            table="event_moderation_logs",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
