# Generated by Django 6.0.3 on 2026-04-02 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'checkin_logs',
                'ordering': ['-scanned_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('cancel_requested', 'Cancel requested'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked in')], default='pending', max_length=24)),
                ('form_answers_jsonb', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_registrations',
                'ordering': ['-registered_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationCancellationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registration_cancellation_requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ticket_code', models.CharField(max_length=50, unique=True)),
                ('qr_payload', models.TextField()),
                ('qr_signature', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='issued', max_length=20)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketQrToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
            ],
            options={
                'db_table': 'ticket_qr_tokens',
                'ordering': ['-valid_from'],
                'abstract': False,
            },
        ),
    ]
