# Generated by Django 6.0.3 on 2026-04-02 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlog',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationcancellationrequest',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='registrations.eventregistration'),
        ),
        migrations.AddField(
            model_name='registrationcancellationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cancellation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='registrations.eventregistration'),
        ),
        migrations.AddField(
            model_name='checkinlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_logs', to='registrations.ticket'),
        ),
        migrations.AddField(
            model_name='ticketqrtoken',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='registrations.ticket'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='event_regis_event_i_a22351_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', 'status'], name='event_regis_user_id_d6b1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'created_at'], name='event_regis_event_i_1c2482_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='uq_event_registrations_event_user'),
        ),
        migrations.AddIndex(
            model_name='registrationcancellationrequest',
            index=models.Index(fields=['registration', 'status'], name='registratio_registr_1e260c_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationcancellationrequest',
            index=models.Index(fields=['status', 'created_at'], name='registratio_status_e8122b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_code'], name='tickets_ticket__2ef6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'expires_at'], name='tickets_status_5d60c7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['registration'], name='tickets_registr_623855_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinlog',
            index=models.Index(fields=['ticket', 'scanned_at'], name='checkin_log_ticket__e1c325_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinlog',
            index=models.Index(fields=['result', 'scanned_at'], name='checkin_log_result_b415c2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketqrtoken',
            index=models.Index(fields=['ticket', 'valid_to'], name='ticket_qr_t_ticket__bea493_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketqrtoken',
            index=models.Index(fields=['valid_from', 'valid_to'], name='ticket_qr_t_valid_f_8cb9fc_idx'),
        ),
    ]
