# Generated by Django 5.1.15 on 2026-04-12 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0003_remove_registrationformfield_uq_registration_fields_event_key_and_more",
        ),
        ("registrations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkinlog",
            options={"ordering": ["-checked_in_at", "-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="checkinlog",
            name="checkin_log_ticket__e1c325_idx",
        ),
        migrations.RemoveIndex(
            model_name="checkinlog",
            name="checkin_log_result_b415c2_idx",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_status_5d60c7_idx",
        ),
        migrations.RenameField(
            model_name="registrationcancellationrequest",
            old_name="reviewed_by",
            new_name="reviewed_by_user",
        ),
        migrations.RemoveField(
            model_name="checkinlog",
            name="failure_reason",
        ),
        migrations.RemoveField(
            model_name="checkinlog",
            name="scanned_at",
        ),
        migrations.RemoveField(
            model_name="checkinlog",
            name="scanned_by",
        ),
        migrations.AddField(
            model_name="checkinlog",
            name="checked_in_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="checkinlog",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="checkin_logs",
                to="events.event",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="checkinlog",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkinlog",
            name="scanner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkin_scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="answers_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationcancellationrequest",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cancellation_requests",
                to="events.event",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registrationcancellationrequest",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="registrationcancellationrequest",
            name="requester_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="issued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="ticket",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketqrtoken",
            name="issued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="checkinlog",
            name="result",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("invalid_format", "Invalid format"),
                    ("invalid_ticket", "Invalid ticket"),
                    ("already_checked_in", "Already checked in"),
                    ("event_unavailable", "Event unavailable"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="checkinlog",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkin_logs",
                to="registrations.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("registered", "Registered"),
                    ("waitlisted", "Waitlisted"),
                    ("cancel_pending", "Cancel pending"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                    ("checked_in", "Checked in"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="registrationcancellationrequest",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="qr_payload",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("used", "Used"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="valid",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="checkinlog",
            index=models.Index(
                fields=["ticket", "checked_in_at"],
                name="checkin_log_ticket__e0a2d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkinlog",
            index=models.Index(
                fields=["event", "checked_in_at"], name="checkin_log_event_i_385731_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "issued_at"], name="tickets_status_01eee7_idx"
            ),
        ),
    ]
