# Generated by Django 6.0.3 on 2026-04-02 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'campuses',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='campuses_name_7c728b_idx'), models.Index(fields=['code'], name='campuses_code_3dfa90_idx')],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='locations.campus')),
            ],
            options={
                'db_table': 'buildings',
                'ordering': ['campus__name', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='locations.building')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['building__name', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['campus', 'name'], name='buildings_campus__62cb61_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['campus', 'code'], name='buildings_campus__45c9a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('campus', 'code'), name='uq_buildings_campus_code'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'name'], name='rooms_buildin_e636c2_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'code'], name='rooms_buildin_004a86_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'code'), name='uq_rooms_building_code'),
        ),
    ]
