# Generated by Django 5.1.15 on 2026-04-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campus",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="buildings",
                to="locations.campus",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="rooms",
                to="locations.building",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
