# Generated by Django 5.2.13 on 2026-04-12 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userauthidentity",
            name="uq_user_auth_provider_uid",
        ),
        migrations.RemoveIndex(
            model_name="userauthidentity",
            name="user_auth_i_last_us_88c4d6_idx",
        ),
        migrations.RenameField(
            model_name="userauthidentity",
            old_name="is_verified",
            new_name="email_verified",
        ),
        migrations.RenameField(
            model_name="userauthidentity",
            old_name="last_used_at",
            new_name="last_login_at",
        ),
        migrations.RenameField(
            model_name="userauthidentity",
            old_name="provider_uid",
            new_name="provider_subject",
        ),
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("banned", "Banned"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="class_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="faculty",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userauthidentity",
            name="password_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="assigned_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userrole",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_user_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userauthidentity",
            name="provider",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("github", "GitHub"),
                    ("passkey", "Passkey"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="user_roles",
                to="users.role",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["account_status"], name="users_account_33da0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userauthidentity",
            index=models.Index(
                fields=["last_login_at"], name="user_auth_i_last_lo_766893_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userauthidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_subject"),
                name="uq_user_auth_provider_subject",
            ),
        ),
    ]
