# Generated by Django 5.1.15 on 2026-04-12 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="supportmessage",
            name="support_mes_sender__c1d4b2_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportticket",
            name="support_tic_user_id_88b410_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportticket",
            name="support_tic_priorit_21ff2f_idx",
        ),
        migrations.RemoveIndex(
            model_name="supportticket",
            name="support_tic_event_i_70d79e_idx",
        ),
        migrations.RenameField(
            model_name="supportmessage",
            old_name="message",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="supportmessage",
            old_name="is_internal",
            new_name="is_staff",
        ),
        migrations.RenameField(
            model_name="supportticket",
            old_name="title",
            new_name="subject",
        ),
        migrations.RemoveField(
            model_name="supportmessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="event",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="resolved_at",
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="author_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("account", "Account"),
                    ("event", "Event"),
                    ("payment", "Payment"),
                    ("technical", "Technical"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="supportmessage",
            index=models.Index(
                fields=["author_user", "created_at"],
                name="support_mes_author__6fc210_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["user", "created_at"], name="support_tic_user_id_eb143a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["status", "priority", "updated_at"],
                name="support_tic_status_4b5f5b_idx",
            ),
        ),
    ]
