[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          tail
    Path          /app/logs/audit.json
    Parser        json
    Tag           uevent.audit
    DB            /tmp/flb_audit.db
    Mem_Buf_Limit 10MB
    Skip_Long_Lines On

[FILTER]
    Name          modify
    Match         uevent.audit
    Add           service uevent-backend

[OUTPUT]
    Name          opensearch
    Match         uevent.audit
    Host          opensearch
    Port          9200
    Index         uevent-audit
    Logstash_Format On
    Logstash_Prefix uevent-audit
    Suppress_Type_Name On
    Replace_Dots  On
    Retry_Limit   False
