# Generated by Django 5.1.15 on 2026-04-12 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notificationrecipient",
            name="notificatio_user_id_b285c1_idx",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="content",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="notificationtemplate",
            old_name="body_template",
            new_name="message_template",
        ),
        migrations.RenameField(
            model_name="notificationtemplate",
            old_name="subject_template",
            new_name="title_template",
        ),
        migrations.AddField(
            model_name="notification",
            name="audience_type",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("students", "Students"),
                    ("organizers", "Organizers"),
                    ("admins", "Admins"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("announcement", "Announcement"),
                    ("alert", "Alert"),
                    ("reminder", "Reminder"),
                    ("promotion", "Promotion"),
                    ("invite", "Invite"),
                    ("ticket_confirm", "Ticket Confirm"),
                ],
                default="announcement",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="notificationrecipient",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("read", "Read"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["user", "delivery_status"],
                name="notificatio_user_id_05312e_idx",
            ),
        ),
    ]
